services:
  neo4j:
    image: neo4j:5.10
    container_name: neo4j-banco
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      # autenticação
      - NEO4J_AUTH=neo4j/neo4j1234

    volumes:
      - ./data:/data
